/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SectionsRouteRouteImport } from './routes/sections/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionsIndexRouteImport } from './routes/sections/index'
import { Route as SectionsSectionIndexRouteImport } from './routes/sections/$section/index'
import { Route as SectionsSectionIdRouteImport } from './routes/sections/$section/$id'

const SectionsRouteRoute = SectionsRouteRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionsIndexRoute = SectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SectionsRouteRoute,
} as any)
const SectionsSectionIndexRoute = SectionsSectionIndexRouteImport.update({
  id: '/$section/',
  path: '/$section/',
  getParentRoute: () => SectionsRouteRoute,
} as any)
const SectionsSectionIdRoute = SectionsSectionIdRouteImport.update({
  id: '/$section/$id',
  path: '/$section/$id',
  getParentRoute: () => SectionsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sections': typeof SectionsRouteRouteWithChildren
  '/sections/': typeof SectionsIndexRoute
  '/sections/$section/$id': typeof SectionsSectionIdRoute
  '/sections/$section': typeof SectionsSectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sections': typeof SectionsIndexRoute
  '/sections/$section/$id': typeof SectionsSectionIdRoute
  '/sections/$section': typeof SectionsSectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sections': typeof SectionsRouteRouteWithChildren
  '/sections/': typeof SectionsIndexRoute
  '/sections/$section/$id': typeof SectionsSectionIdRoute
  '/sections/$section/': typeof SectionsSectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sections'
    | '/sections/'
    | '/sections/$section/$id'
    | '/sections/$section'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sections' | '/sections/$section/$id' | '/sections/$section'
  id:
    | '__root__'
    | '/'
    | '/sections'
    | '/sections/'
    | '/sections/$section/$id'
    | '/sections/$section/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SectionsRouteRoute: typeof SectionsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sections': {
      id: '/sections'
      path: '/sections'
      fullPath: '/sections'
      preLoaderRoute: typeof SectionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sections/': {
      id: '/sections/'
      path: '/'
      fullPath: '/sections/'
      preLoaderRoute: typeof SectionsIndexRouteImport
      parentRoute: typeof SectionsRouteRoute
    }
    '/sections/$section/': {
      id: '/sections/$section/'
      path: '/$section'
      fullPath: '/sections/$section'
      preLoaderRoute: typeof SectionsSectionIndexRouteImport
      parentRoute: typeof SectionsRouteRoute
    }
    '/sections/$section/$id': {
      id: '/sections/$section/$id'
      path: '/$section/$id'
      fullPath: '/sections/$section/$id'
      preLoaderRoute: typeof SectionsSectionIdRouteImport
      parentRoute: typeof SectionsRouteRoute
    }
  }
}

interface SectionsRouteRouteChildren {
  SectionsIndexRoute: typeof SectionsIndexRoute
  SectionsSectionIdRoute: typeof SectionsSectionIdRoute
  SectionsSectionIndexRoute: typeof SectionsSectionIndexRoute
}

const SectionsRouteRouteChildren: SectionsRouteRouteChildren = {
  SectionsIndexRoute: SectionsIndexRoute,
  SectionsSectionIdRoute: SectionsSectionIdRoute,
  SectionsSectionIndexRoute: SectionsSectionIndexRoute,
}

const SectionsRouteRouteWithChildren = SectionsRouteRoute._addFileChildren(
  SectionsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectionsRouteRoute: SectionsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
