/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionsIndexRouteImport } from './routes/sections/index'
import { Route as ContextIndexRouteImport } from './routes/context/index'
import { Route as ContextCategoryRouteImport } from './routes/context/$category'
import { Route as SectionsSectionRouteRouteImport } from './routes/sections/$section/route'
import { Route as SectionsSectionIndexRouteImport } from './routes/sections/$section/index'
import { Route as SectionsSectionIdRouteImport } from './routes/sections/$section/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionsIndexRoute = SectionsIndexRouteImport.update({
  id: '/sections/',
  path: '/sections/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextIndexRoute = ContextIndexRouteImport.update({
  id: '/context/',
  path: '/context/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextCategoryRoute = ContextCategoryRouteImport.update({
  id: '/context/$category',
  path: '/context/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionsSectionRouteRoute = SectionsSectionRouteRouteImport.update({
  id: '/sections/$section',
  path: '/sections/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionsSectionIndexRoute = SectionsSectionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SectionsSectionRouteRoute,
} as any)
const SectionsSectionIdRoute = SectionsSectionIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SectionsSectionRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sections/$section': typeof SectionsSectionRouteRouteWithChildren
  '/context/$category': typeof ContextCategoryRoute
  '/context': typeof ContextIndexRoute
  '/sections': typeof SectionsIndexRoute
  '/sections/$section/$id': typeof SectionsSectionIdRoute
  '/sections/$section/': typeof SectionsSectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/context/$category': typeof ContextCategoryRoute
  '/context': typeof ContextIndexRoute
  '/sections': typeof SectionsIndexRoute
  '/sections/$section/$id': typeof SectionsSectionIdRoute
  '/sections/$section': typeof SectionsSectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sections/$section': typeof SectionsSectionRouteRouteWithChildren
  '/context/$category': typeof ContextCategoryRoute
  '/context/': typeof ContextIndexRoute
  '/sections/': typeof SectionsIndexRoute
  '/sections/$section/$id': typeof SectionsSectionIdRoute
  '/sections/$section/': typeof SectionsSectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sections/$section'
    | '/context/$category'
    | '/context'
    | '/sections'
    | '/sections/$section/$id'
    | '/sections/$section/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/context/$category'
    | '/context'
    | '/sections'
    | '/sections/$section/$id'
    | '/sections/$section'
  id:
    | '__root__'
    | '/'
    | '/sections/$section'
    | '/context/$category'
    | '/context/'
    | '/sections/'
    | '/sections/$section/$id'
    | '/sections/$section/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SectionsSectionRouteRoute: typeof SectionsSectionRouteRouteWithChildren
  ContextCategoryRoute: typeof ContextCategoryRoute
  ContextIndexRoute: typeof ContextIndexRoute
  SectionsIndexRoute: typeof SectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sections/': {
      id: '/sections/'
      path: '/sections'
      fullPath: '/sections'
      preLoaderRoute: typeof SectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context/': {
      id: '/context/'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof ContextIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context/$category': {
      id: '/context/$category'
      path: '/context/$category'
      fullPath: '/context/$category'
      preLoaderRoute: typeof ContextCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sections/$section': {
      id: '/sections/$section'
      path: '/sections/$section'
      fullPath: '/sections/$section'
      preLoaderRoute: typeof SectionsSectionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sections/$section/': {
      id: '/sections/$section/'
      path: '/'
      fullPath: '/sections/$section/'
      preLoaderRoute: typeof SectionsSectionIndexRouteImport
      parentRoute: typeof SectionsSectionRouteRoute
    }
    '/sections/$section/$id': {
      id: '/sections/$section/$id'
      path: '/$id'
      fullPath: '/sections/$section/$id'
      preLoaderRoute: typeof SectionsSectionIdRouteImport
      parentRoute: typeof SectionsSectionRouteRoute
    }
  }
}

interface SectionsSectionRouteRouteChildren {
  SectionsSectionIdRoute: typeof SectionsSectionIdRoute
  SectionsSectionIndexRoute: typeof SectionsSectionIndexRoute
}

const SectionsSectionRouteRouteChildren: SectionsSectionRouteRouteChildren = {
  SectionsSectionIdRoute: SectionsSectionIdRoute,
  SectionsSectionIndexRoute: SectionsSectionIndexRoute,
}

const SectionsSectionRouteRouteWithChildren =
  SectionsSectionRouteRoute._addFileChildren(SectionsSectionRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectionsSectionRouteRoute: SectionsSectionRouteRouteWithChildren,
  ContextCategoryRoute: ContextCategoryRoute,
  ContextIndexRoute: ContextIndexRoute,
  SectionsIndexRoute: SectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
